---
- name: Attempting to import fastestmirror plugin tasks
  tags: yum_plugins
  become: true
  import_tasks: yum_plugin_fastestmirror.yml
  when:
    - yum_plugin_fastestmirror.enabled is defined
    - yum_plugin_fastestmirror.enabled|bool

- name: Attempting to import pre-transaction-actions plugin tasks
  tags: yum_plugins
  become: true
  import_tasks: yum_plugin_pre_transaction_actions.yml
  when:
    - yum_plugin_pre_transaction_actions.enabled is defined
    - yum_plugin_pre_transaction_actions.enabled|bool

- name: Attempting to import post-transaction-actions plugin tasks
  tags: yum_plugins
  become: true
  import_tasks: yum_plugin_post_transaction_actions.yml
  when:
    - yum_plugin_post_transaction_actions.enabled is defined
    - yum_plugin_post_transaction_actions.enabled|bool
...
